#!/usr/bin/env bash
# Create the publisher account on the local PDS and write credentials for ofw + Sidekar.
set -euo pipefail

PDS_URL="${PDS_URL:-http://127.0.0.1:2583}"
HANDLE="${OFW_HANDLE:-publisher.pds.test}"
EMAIL="${OFW_EMAIL:-publisher@mail.test}"
PASSWORD="${OFW_PASSWORD:-publisher-pass-change-me}"
OUT_DIR="${OUT_DIR:-$(cd "$(dirname "$0")/.." && pwd)/.local}"
CREDS="${OUT_DIR}/publisher.env"

mkdir -p "$OUT_DIR"

echo "Waiting for PDS at ${PDS_URL}..."
for i in $(seq 1 60); do
  if curl -fsS "${PDS_URL}/xrpc/_health" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
curl -fsS "${PDS_URL}/xrpc/_health" >/dev/null

# Try create; if exists, createSession instead
CREATE=$(curl -sS -X POST "${PDS_URL}/xrpc/com.atproto.server.createAccount" \
  -H 'content-type: application/json' \
  -d "$(node -e "console.log(JSON.stringify({handle:process.argv[1],email:process.argv[2],password:process.argv[3]}))" "$HANDLE" "$EMAIL" "$PASSWORD")" \
  || true)

if echo "$CREATE" | grep -q accessJwt; then
  DID=$(echo "$CREATE" | node -e "let s='';process.stdin.on('data',d=>s+=d);process.stdin.on('end',()=>console.log(JSON.parse(s).did))")
  echo "Created account ${HANDLE} → ${DID}"
else
  echo "createAccount response: $CREATE"
  SESSION=$(curl -sS -X POST "${PDS_URL}/xrpc/com.atproto.server.createSession" \
    -H 'content-type: application/json' \
    -d "$(node -e "console.log(JSON.stringify({identifier:process.argv[1],password:process.argv[2]}))" "$HANDLE" "$PASSWORD")")
  if ! echo "$SESSION" | grep -q accessJwt; then
    echo "Failed to create or login publisher: $SESSION" >&2
    exit 1
  fi
  DID=$(echo "$SESSION" | node -e "let s='';process.stdin.on('data',d=>s+=d);process.stdin.on('end',()=>console.log(JSON.parse(s).did))")
  echo "Using existing account ${HANDLE} → ${DID}"
fi

cat >"$CREDS" <<EOF
# Generated by bootstrap-publisher.sh — local demo only
OFW_PDS=${PDS_URL}
OFW_IDENTIFIER=${HANDLE}
OFW_PASSWORD=${PASSWORD}
OFW_AUTHOR_DID=${DID}
AUTHOR_DID=${DID}
PDS_URL=${PDS_URL}
EOF

# Also write DID for Sidekar volume
echo "$DID" >"${OUT_DIR}/author.did"
echo "Wrote ${CREDS}"
cat "$CREDS"
