/** 256 short words for human-readable fingerprints (not BIP39 security). */
export const WORDLIST = [
  'able','acid','aged','also','area','army','away','baby','back','ball',
  'band','bank','base','bath','bear','beat','been','bell','belt','best',
  'bird','blow','blue','boat','body','bomb','bond','bone','book','boom',
  'born','boss','both','bowl','bulk','burn','bush','busy','call','calm',
  'came','camp','card','care','case','cash','cast','cave','cell','chat',
  'chip','city','clam','clan','clap','clay','clip','club','clue','coal',
  'coat','code','coil','coin','cold','come','cook','cool','cope','copy',
  'cord','core','cork','corn','cost','cozy','crab','crew','crop','crow',
  'cube','cult','curb','cure','curl','cute','damp','dare','dark','dart',
  'dash','data','dawn','days','dead','deal','dean','dear','debt','deck',
  'deep','deer','desk','dial','diet','dime','dirt','disc','dish','dock',
  'does','doll','dome','done','door','dose','down','draw','drew','drop',
  'drum','dual','duck','duel','duet','dull','dune','dusk','dust','duty',
  'each','earn','ease','east','easy','edge','else','even','ever','evil',
  'exam','exit','face','fact','fail','fair','fall','fame','farm','fast',
  'fate','fear','feed','feel','feet','fell','felt','file','fill','film',
  'find','fine','fire','firm','fish','fist','five','flag','flat','fled',
  'flew','flip','flow','foam','foil','fold','folk','fond','food','fool',
  'foot','ford','fork','form','fort','foul','four','free','frog','from',
  'fuel','full','fund','fury','fuse','gain','game','gang','gate','gave',
  'gear','gene','gift','girl','give','glad','glow','glue','goal','goat',
  'goes','gold','golf','gone','good','grab','gray','grew','grid','grim',
  'grin','grip','grow','gulf','guru','hail','hair','half','hall','halt',
  'hand','hang','hard','harm','hate','have','hawk','head','heal','heap',
  'hear','heat','heed','heel','held','helm','help','herb','herd','here',
] as const
